// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ucfmoziuukiryyykjkln.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVjZm1veml1dWtpcnl5eWtqa2xuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAxMjc4NTMsImV4cCI6MjA2NTcwMzg1M30.KxQah9Kx94faKtOX7Dm31tCeExy8TkJxTdjxlarA4Gs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);